name: newnormal-test
app: python@3.9
options:
  env:
    - name: FLASK_ENV
      value: production
    - name: DB_HOST
      value: svc.sel5.cloudtype.app
    - name: DB_PORT
      value: '32714'
    - name: DB_USER
      value: root
    - name: DB_PASSWORD
      value: newnormal!
    - name: DB_NAME
      value: newnormal_schema
  ports: 5000
  start: gunicorn -b 0.0.0.0:5000 app:app
context:
  git:
    url: https://github.com/sanggyoon/NewNormal_Test.git
    branch: master
    path: APItest
  preset: python-flask
